version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=my_password
      - MYSQL_DATABASE=my_database
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
    ports:
      - '3306:3306'

  adminer:
    image: adminer:latest
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
